
import sharedImage from "@/assets/our-work/ourWork.jpg"

export const projects: any = [
  {
    id: 1,
    title: "Tiny Sprouts: A Story-driven Edtech Platform",
    tags: ["Branding Identity", "Web & App Design", "Dashboard Design"],
    category: "Web Design",
    overview: "Sprout is a story-driven EdTech platform that bridges communication between students, teachers, and parents.",
    imageUrl: sharedImage,
  },
  {
    id: 2,
    title: "EcoFresh Organics: Nature on Your Screen",
    tags: ["Web Design", "Responsive Design", "SEO"],
    category: "Website Development",
    overview: "A fresh organic brand with a modern, mobile-friendly website optimized for SEO and user engagement.",
    imageUrl: sharedImage,
  },
  {
    id: 3,
    title: "QuickCart: Grocery Shopping App UI",
    tags: ["App UI", "User Flow", "Mobile Experience"],
    category: "App Design",
    overview: "QuickCart is a grocery delivery app designed for quick navigation, intuitive flow, and delightful visuals.",
    imageUrl: sharedImage,
  },
  {
    id: 4,
    title: "NovaNectar Logo Suite",
    tags: ["Logo Design", "Brand Identity", "Typography"],
    category: "Logo Design",
    overview: "Elegant and minimal logo suite designed for NovaNectar’s cosmetic product line.",
    imageUrl: sharedImage,
  },
  {
    id: 5,
    title: "Cafe Mocha Instagram Rebranding",
    tags: ["Instagram Strategy", "Content Design", "Engagement"],
    category: "Social Media Management",
    overview: "Social presence uplift for Cafe Mocha with custom templates and daily engagement campaigns.",
    imageUrl: sharedImage,
  },
  {
    id: 6,
    title: "ZippyPay Wallet App",
    tags: ["App Development", "Fintech", "Security"],
    category: "App Development",
    overview: "Developed a secure and smooth wallet app using React Native and Firebase for real-time money transfers.",
    imageUrl: sharedImage,
  },
  {
    id: 7,
    title: "Fitology Website Revamp",
    tags: ["UX Redesign", "Fitness Niche", "Animations"],
    category: "Web Design",
    overview: "Rebuilt Fitology's website with clean layout, motivating visuals, and smooth scroll animations.",
    imageUrl: sharedImage,
  },
  {
    id: 8,
    title: "BuildIt Construction Co. Web Portal",
    tags: ["Dashboard Design", "Project Tracker", "Admin Panel"],
    category: "Website Development",
    overview: "A robust internal project management system for a construction company, with real-time task updates.",
    imageUrl: sharedImage,
  },
  {
    id: 9,
    title: "StoryGram Kids App",
    tags: ["Child-friendly UI", "Dark Mode", "Safe Login"],
    category: "App Design",
    overview: "Fun and safe app interface for children to read and share visual stories. Light/dark toggle and voice interaction.",
    imageUrl: sharedImage,
  },
  {
    id: 10,
    title: "CraveBox Logo Exploration",
    tags: ["Hand-drawn Logo", "Food Industry", "Color Study"],
    category: "Logo Design",
    overview: "A bold logo with hand-lettered typography and playful illustrations for a snack subscription brand.",
    imageUrl: sharedImage,
  },
  {
    id: 11,
    title: "GlowBeauty Reels Campaign",
    tags: ["Short-form Video", "Engagement Boost", "Hashtag Strategy"],
    category: "Social Media Management",
    overview: "Created weekly reel series for GlowBeauty that increased Instagram reach by 2.5x in 30 days.",
    imageUrl: sharedImage,
  },
  {
    id: 12,
    title: "Finza Expense Tracker App",
    tags: ["Budget Charts", "Push Alerts", "Dark Theme"],
    category: "App Development",
    overview: "Designed and developed a personal finance app for tracking spending, saving, and financial goals.",
    imageUrl: sharedImage,
  },
  {
    id: 13,
    title: "InspireCo Portfolio Website",
    tags: ["Minimal Design", "Portfolio", "Fast Load"],
    category: "Web Design",
    overview: "A clean portfolio website optimized for speed and SEO, with smooth page transitions.",
    imageUrl: sharedImage,
  },
  {
    id: 14,
    title: "Aurora Admin Panel",
    tags: ["Backend UI", "Access Control", "Charts"],
    category: "Website Development",
    overview: "Admin dashboard for Aurora marketplace with user roles, order tracking, and analytics.",
    imageUrl: sharedImage,
  },
  {
    id: 15,
    title: "Swifty Rideshare App UI Kit",
    tags: ["Wireframe", "User Flow", "Prototyping"],
    category: "App Design",
    overview: "Complete UI Kit designed in Figma for a rideshare app with maps, trip history, and driver profiles.",
    imageUrl: sharedImage,
  },
  {
    id: 16,
    title: "PixelPets Logo",
    tags: ["Mascot Design", "Pixel Style", "Cute Aesthetic"],
    category: "Logo Design",
    overview: "Logo design for a pet-themed pixel game with a fun, colorful identity that appeals to kids.",
    imageUrl: sharedImage,
  },
  {
    id: 17,
    title: "HealWell Facebook Strategy",
    tags: ["Facebook Ads", "Lead Magnet", "Carousel Post Design"],
    category: "Social Media Management",
    overview: "Developed a Facebook content and ad strategy for a wellness clinic focused on local reach.",
    imageUrl: sharedImage,
  },
  {
    id: 18,
    title: "EduZone Learning App",
    tags: ["Video Lessons", "Progress Tracker", "React Native"],
    category: "App Development",
    overview: "Full-stack learning app with admin panel, student login, and downloadable courses.",
    imageUrl: sharedImage,
  },
  {
    id: 19,
    title: "LensCraft Studio Website",
    tags: ["Photography Showcase", "Gallery View", "Booking System"],
    category: "Web Design",
    overview: "Portfolio website for a photographer with fullscreen gallery, client testimonials, and booking form.",
    imageUrl: sharedImage,
  },
  {
    id: 20,
    title: "CityLink Property Dashboard",
    tags: ["Real Estate", "Live Map", "User Roles"],
    category: "Website Development",
    overview: "A powerful dashboard for managing listings, live locations, and client communication in real estate.",
    imageUrl: sharedImage,
  },
];
